title: Groups in Galway
tagline: The annual conference series homepage
description: The homepage for the annual conference series "Groups in Galway".
author: GiG Organizers
url: "https://groupsingalway.github.io"
baseurl: ""

# Registration form. If closed, put "".
registration: "https://forms.office.com/e/1Zkx262cq5"

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap 
  - jekyll-seo-tag

collections:
  abstracts:
    output: false

exclude:
  - LICENSE
  - .gitignore
  - README.md
  - docs
  - participants/extract.py
  - "*.xlsx"
  - build.sh
  - "abstracts/2024abs/*"

include: 
  - .htaccess 

# theme: jekyll-theme-midnight